import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'dashboard': 'Dashboard',
      'reports': 'Reports',
      'customers': 'Customers',
      'add_customer': 'Add Customer',
      'logout': 'Logout',
      'logout_confirm_title': 'Logout',
      'logout_confirm_msg': 'Are you sure you want to logout?',
      'cancel': 'Cancel',
      'welcome': 'Welcome',
      'total_customers': 'Total Customers',
      'this_month': 'This Month',
      'pending': 'Pending',
      'ready': 'Ready',
      'recent_customers': 'Recent Customers',
      'view_all': 'View All',
      'no_customers_yet': 'No customers yet',
      'add_first_customer': 'Add your first customer to get started',
      'select_language': 'Select Language',
      'delete_customer': 'Delete Customer',
      'delete_confirm_msg': 'Remove customer? This cannot be undone.',
      'customer_deleted': 'Customer deleted',
      'failed_to_delete': 'Failed to delete: ',
      'search_hint': 'Search by name or phone...',
      'loading_customers': 'Loading customers...',
      'tap_to_add': 'Tap + to add your first customer',
      'no_customers_found': 'No customers found',
      'customer_info': 'Customer Information',
      'full_name': 'Full Name *',
      'phone_number': 'Phone Number *',
      'address': 'Address',
      'notes': 'Notes',
      'save_customer': 'Save Customer',
      'name_required': 'Name is required',
      'phone_required': 'Phone number is required',
      'phone_invalid': 'Enter a valid phone number',
      'customer_added': 'Customer added successfully!',
      'failed_to_add': 'Failed to add customer: ',
      'customer_details': 'Customer Details',
      'measurements': 'Measurements',
      'no_measurements': 'No measurements recorded',
      'add_measurement': 'Add Measurement',
      'view_card': 'View Card',
      'price': 'Price',
      'advance': 'Advance',
      'status': 'Status',
      'delivery_date': 'Delivery Date',
      'edit': 'Edit',
      'delete': 'Delete',
      'payments': 'Payments',
      'total_revenue': 'Total Revenue',
      'monthly_orders': 'Monthly Orders',
      'shirt': 'Shirt',
      'pant': 'Pant',
      'kurta': 'Kurta',
      'blouse': 'Blouse',
      'sadra': 'Sadra',
      'in-progress': 'In Progress',
      'completed': 'Completed',
      'delivered': 'Delivered',
      'payment': 'Payment',
      'pdf': 'PDF',
      'design': 'Design',
      'paid': 'Paid',
      'balance': 'Bal',
      'set_as': 'Set as',
      'add': 'Add',
      'no_customer_data': 'No customer data',
      'loading_measurements': 'Loading measurements...',
      'delete_measurement': 'Delete Measurement',
      'delete_measurement_confirm': 'Are you sure you want to delete this measurement?',
      'theme': 'Theme',
      'light': 'Light',
      'dark': 'Dark',
      'system': 'System',
      'settings': 'Settings',
      'shop_settings': 'Shop Settings',
      'shop_name': 'Shop Name',
      'owner_name': 'Owner Name',
      'shop_phone': 'Shop Phone',
      'shop_address': 'Shop Address',
      'gstin': 'GSTIN / Tax ID',
      'terms_conditions': 'Terms & Conditions',
      'select_logo': 'Select Shop Logo',
      'save_settings': 'Save Settings',
      'settings_saved': 'Settings saved successfully!',
      'garment_type': 'Garment Type',
      'design_image_optional': 'Design Image (Optional)',
      'tap_to_add_design_image': 'Tap to add design image',
      'camera_or_gallery': 'Camera or Gallery',
      'order_details': 'Order Details',
      'select_delivery_date': 'Select delivery date',
      'save_measurement': 'Save Measurement',
      'field_length': 'Length',
      'field_chest': 'Chest',
      'field_waist': 'Waist',
      'field_stomach': 'Stomach',
      'field_shoulder': 'Shoulder',
      'field_sleeve': 'Sleeve',
      'field_collar': 'Collar',
      'field_neck': 'Neck',
      'field_armhole': 'Armhole',
      'field_biceps': 'Biceps',
      'field_pantLength': 'Pant Length',
      'field_seat': 'Seat',
      'field_thigh': 'Thigh',
      'field_knee': 'Knee',
      'field_bottom': 'Bottom',
      'field_rise': 'Rise',
      'field_hip': 'Hip',
      'field_kurtalength': 'Kurta Length',
      'field_kurtaghera': 'Ghera',
      'field_blouseLength': 'Blouse Length',
      'field_bust': 'Bust',
      'field_blouseWaist': 'Blouse Waist',
      'field_backNeck': 'Back Neck',
      'field_frontNeck': 'Front Neck',
      'field_blouseSleeve': 'Blouse Sleeve',
    },
    'mr': {
      'dashboard': 'डॅशबोर्ड',
      'reports': 'अहवाल',
      'customers': 'ग्राहक',
      'add_customer': 'ग्राहक जोडा',
      'logout': 'बाहेर पडा',
      'logout_confirm_title': 'बाहेर पडा',
      'logout_confirm_msg': 'तुम्हाला खात्री आहे की तुम्ही बाहेर पडू इच्छिता?',
      'cancel': 'रद्द करा',
      'welcome': 'स्वागत आहे',
      'total_customers': 'एकूण ग्राहक',
      'this_month': 'या महिन्यात',
      'pending': 'प्रलंबित',
      'ready': 'तयार',
      'recent_customers': 'अलीकडील ग्राहक',
      'view_all': 'सर्व पहा',
      'no_customers_yet': 'अद्याप कोणतेही ग्राहक नाहीत',
      'add_first_customer': 'सुरू करण्यासाठी तुमचा पहिला ग्राहक जोडा',
      'select_language': 'भाषा निवडा',
      'delete_customer': 'ग्राहक हटवा',
      'delete_confirm_msg': 'ग्राहक काढून टाकायचा? हे पूर्ववत केले जाऊ शकत नाही.',
      'customer_deleted': 'ग्राहक हटवला',
      'failed_to_delete': 'हटवण्यात अयशस्वी: ',
      'search_hint': 'नाव किंवा फोनद्वारे शोधा...',
      'loading_customers': 'ग्राहक लोड होत आहेत...',
      'tap_to_add': 'पहिला ग्राहक जोडण्यासाठी + दाबा',
      'no_customers_found': 'कोणतेही ग्राहक आढळले नाहीत',
      'customer_info': 'ग्राहकाची माहिती',
      'full_name': 'पूर्ण नाव *',
      'phone_number': 'फोन नंबर *',
      'address': 'पत्ता',
      'notes': 'टीप',
      'save_customer': 'ग्राहक जतन करा',
      'name_required': 'नाव आवश्यक आहे',
      'phone_required': 'फोन नंबर आवश्यक आहे',
      'phone_invalid': 'वैध फोन नंबर प्रविष्ट करा',
      'customer_added': 'ग्राहक यशस्वीरित्या जोडला गेला!',
      'failed_to_add': 'ग्राहक जोडण्यात अयशस्वी: ',
      'customer_details': 'ग्राहकाचा तपशील',
      'measurements': 'मापे',
      'no_measurements': 'कोणतीही मापे नोंदवलेली नाहीत',
      'add_measurement': 'माप जोडा',
      'view_card': 'कार्ड पहा',
      'price': 'किंमत',
      'advance': 'अगाऊ रक्कम',
      'status': 'स्थिती',
      'delivery_date': 'डिलिव्हरी तारीख',
      'edit': 'संपादन करा',
      'delete': 'हटवा',
      'payments': 'पेमेंट्स',
      'total_revenue': 'एकूण महसूल',
      'monthly_orders': 'मासिक ऑर्डर्स',
      'shirt': 'शर्ट',
      'pant': 'पँट',
      'kurta': 'कुर्ता',
      'blouse': 'ब्लाउज',
      'sadra': 'सदरा',
      'in-progress': 'चालू आहे',
      'completed': 'पूर्ण झाले',
      'delivered': 'वितरित',
      'payment': 'पेमेंट',
      'pdf': 'पीडीएफ',
      'design': 'डिझाईन',
      'paid': 'भरले',
      'balance': 'बाकी',
      'set_as': 'असे सेट करा',
      'add': 'जोडा',
      'no_customer_data': 'ग्राहकाचा डेटा नाही',
      'loading_measurements': 'मापे लोड होत आहेत...',
      'delete_measurement': 'माप हटवा',
      'delete_measurement_confirm': 'तुम्हाला खात्री आहे की तुम्ही हे माप हटवू इच्छिता?',
      'theme': 'थीम',
      'light': 'प्रकाशमय',
      'dark': 'गडद',
      'system': 'सिस्टम',
      'settings': 'सेटिंग्ज',
      'shop_settings': 'दुकान सेटिंग्ज',
      'shop_name': 'दुकानाचे नाव',
      'owner_name': 'मालकाचे नाव',
      'shop_phone': 'दुकान फोन',
      'shop_address': 'दुकानाचा पत्ता',
      'gstin': 'जीएसटीआयएन / कर क्रमांक',
      'terms_conditions': 'नियम आणि अटी',
      'select_logo': 'दुकानाचे लोगो निवडा',
      'save_settings': 'सेटिंग्ज जतन करा',
      'settings_saved': 'सेटिंग्ज यशस्वीरित्या जतन केल्या!',
      'garment_type': 'कपड्याचा प्रकार',
      'design_image_optional': 'डिझाईन चित्र (पर्यायी)',
      'tap_to_add_design_image': 'डिझाईन चित्र जोडण्यासाठी टॅप करा',
      'camera_or_gallery': 'कॅमेरा किंवा गॅलरी',
      'order_details': 'ऑर्डर तपशील',
      'select_delivery_date': 'डिलिव्हरी तारीख निवडा',
      'save_measurement': 'माप जतन करा',
      'field_length': 'लांबी (Length)',
      'field_chest': 'छाती (Chest)',
      'field_waist': 'कंबर (Waist)',
      'field_stomach': 'पोट (Stomach)',
      'field_shoulder': 'खांदा (Shoulder)',
      'field_sleeve': 'बाही (Sleeve)',
      'field_collar': 'गळा (Collar)',
      'field_neck': 'मान (Neck)',
      'field_armhole': 'मुंडा (Armhole)',
      'field_biceps': 'दंडघेर (Biceps)',
      'field_pantLength': 'पँट लांबी (Pant Length)',
      'field_seat': 'सीट (Seat)',
      'field_thigh': 'मांडी (Thigh)',
      'field_knee': 'गुडघा (Knee)',
      'field_bottom': 'बॉटम (Bottom)',
      'field_rise': 'किस्त (Rise)',
      'field_hip': 'कमर (Hip)',
      'field_kurtalength': 'कुर्ता लांबी (Kurta Length)',
      'field_kurtaghera': 'घेरा (Ghera)',
      'field_blouseLength': 'ब्लाउज लांबी (Blouse Length)',
      'field_bust': 'छाती (Bust)',
      'field_blouseWaist': 'ब्लाउज कंबर (Blouse Waist)',
      'field_backNeck': 'मागील गळा (Back Neck)',
      'field_frontNeck': 'पुढील गळा (Front Neck)',
      'field_blouseSleeve': 'ब्लाउज बाही (Blouse Sleeve)',
    },
    'hi': {
      'dashboard': 'डैशबोर्ड',
      'reports': 'रिपोर्ट्स',
      'customers': 'ग्राहक',
      'add_customer': 'ग्राहक जोड़ें',
      'logout': 'लॉगआउट',
      'logout_confirm_title': 'लॉगआउट',
      'logout_confirm_msg': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
      'cancel': 'रद्द करें',
      'welcome': 'स्वागत है',
      'total_customers': 'कुल ग्राहक',
      'this_month': 'इस महीने',
      'pending': 'लंबित',
      'ready': 'तैयार',
      'recent_customers': 'हाल के ग्राहक',
      'view_all': 'सभी देखें',
      'no_customers_yet': 'अभी तक कोई ग्राहक नहीं है',
      'add_first_customer': 'शुरू करने के लिए अपना पहला ग्राहक जोड़ें',
      'select_language': 'भाषा चुनें',
      'delete_customer': 'ग्राहक हटाएं',
      'delete_confirm_msg': 'ग्राहक को हटाएं? इसे पूर्ववत नहीं किया जा सकता।',
      'customer_deleted': 'ग्राहक हटा दिया गया',
      'failed_to_delete': 'हटाने में विफल: ',
      'search_hint': 'नाम या फोन से खोजें...',
      'loading_customers': 'ग्राहक लोड हो रहे हैं...',
      'tap_to_add': 'अपना पहला ग्राहक जोड़ने के लिए + दबाएं',
      'no_customers_found': 'कोई ग्राहक नहीं मिला',
      'customer_info': 'ग्राहक की जानकारी',
      'full_name': 'पूरा नाम *',
      'phone_number': 'फ़ोन नंबर *',
      'address': 'पता',
      'notes': 'टिप्पणी',
      'save_customer': 'ग्राहक सहेजें',
      'name_required': 'नाम आवश्यक है',
      'phone_required': 'फ़ोन नंबर आवश्यक है',
      'phone_invalid': 'वैध फ़ोन नंबर दर्ज करें',
      'customer_added': 'ग्राहक सफलतापूर्वक जोड़ा गया!',
      'failed_to_add': 'ग्राहक जोड़ने में विफल: ',
      'customer_details': 'ग्राहक विवरण',
      'measurements': 'माप',
      'no_measurements': 'कोई माप दर्ज नहीं है',
      'add_measurement': 'माप जोड़ें',
      'view_card': 'कार्ड देखें',
      'price': 'मूल्य',
      'advance': 'अग्रिम राशि',
      'status': 'स्थिति',
      'delivery_date': 'डिलिवरी तिथि',
      'edit': 'संपादित करें',
      'delete': 'हटाएं',
      'payments': 'भुगतान',
      'total_revenue': 'कुल आय',
      'monthly_orders': 'मासिक ऑर्डर्स',
      'shirt': 'शर्ट',
      'pant': 'पेंट',
      'kurta': 'कुर्ता',
      'blouse': 'ब्लाउज',
      'sadra': 'सदरा',
      'in-progress': 'प्रगति पर है',
      'completed': 'पूरा हुआ',
      'delivered': 'वितरित',
      'payment': 'भुगतान',
      'pdf': 'पीडीएफ',
      'design': 'डिज़ाइन',
      'paid': 'भुगतान किया',
      'balance': 'शेष',
      'set_as': 'के रूप में सेट करें',
      'add': 'जोड़ें',
      'no_customer_data': 'ग्राहक का कोई डेटा नहीं',
      'loading_measurements': 'माप लोड हो रहे हैं...',
      'delete_measurement': 'माप हटाएं',
      'delete_measurement_confirm': 'क्या आप वाकई इस माप को हटाना चाहते हैं?',
      'theme': 'थीम',
      'light': 'उजाला',
      'dark': 'अंधेरा',
      'system': 'सिस्टम',
      'settings': 'सेटिंग्स',
      'shop_settings': 'दुकान सेटिंग्स',
      'shop_name': 'दुकान का नाम',
      'owner_name': 'मालिक का नाम',
      'shop_phone': 'दुकान फोन',
      'shop_address': 'दुकान का पता',
      'gstin': 'जीएसटीआईएन / टैक्स आईडी',
      'terms_conditions': 'नियम और शर्तें',
      'select_logo': 'दुकान का लोगो चुनें',
      'save_settings': 'सेटिंग्स सहेजें',
      'settings_saved': 'सेटिंग्स सफलतापूर्वक सहेजी गईं!',
      'garment_type': 'कपड़े का प्रकार',
      'design_image_optional': 'डिज़ाइन इमेज (वैकल्पिक)',
      'tap_to_add_design_image': 'डिज़ाइन इमेज जोड़ने के लिए टैप करें',
      'camera_or_gallery': 'कैमरा या गैलरी',
      'order_details': 'ऑर्डर विवरण',
      'select_delivery_date': 'डिलिवरी तिथि चुनें',
      'save_measurement': 'माप सहेजें',
      'field_length': 'लंबाई (Length)',
      'field_chest': 'छाती (Chest)',
      'field_waist': 'कमर (Waist)',
      'field_stomach': 'पेट (Stomach)',
      'field_shoulder': 'कंधा (Shoulder)',
      'field_sleeve': 'आस्तीन (Sleeve)',
      'field_collar': 'कॉलर (Collar)',
      'field_neck': 'गला (Neck)',
      'field_armhole': 'आर्महोल (Armhole)',
      'field_biceps': 'डौल (Biceps)',
      'field_pantLength': 'पेंट लंबाई (Pant Length)',
      'field_seat': 'सीट (Seat)',
      'field_thigh': 'जांघ (Thigh)',
      'field_knee': 'घुटने (Knee)',
      'field_bottom': 'मोहरी (Bottom)',
      'field_rise': 'आसन (Rise)',
      'field_hip': 'हिप (Hip)',
      'field_kurtalength': 'कुर्ता लंबाई (Kurta Length)',
      'field_kurtaghera': 'घेरा (Ghera)',
      'field_blouseLength': 'ब्लाउज लंबाई (Blouse Length)',
      'field_bust': 'सीना (Bust)',
      'field_blouseWaist': 'ब्लाउज कमर (Blouse Waist)',
      'field_backNeck': 'पीछे का गला (Back Neck)',
      'field_frontNeck': 'आगे का गला (Front Neck)',
      'field_blouseSleeve': 'ब्लाउज आस्तीन (Blouse Sleeve)',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'mr', 'hi'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
